### ISSUE TITLE
Feature request: Ability to display scheduled date in EPG search.

### ISSUE THREAD

**Issue by riban-bw** [john-tornblom/TVHGuide#10]
When searching the EPG, all entries over a week away are shown relative to today, e.g. "In two days". This is proving difficult to use. The user ends up counting days from now to find out which day is being referred. May I request an option to show the date of recording?

**Comment by riban-bw** [comment]
Please show day and date, e.g. Monday 07 Jan 2013.

**Comment by john-tornblom** [comment]
First of all, if you click on the event, the complete date and time is displayed beneath the title. 

Regarding the search result list:
I agree that "in 12 days" might not be very helpful and you end up counting days.  However, if the user is not aware of the current date, tomorrow, in two days and so on is easier to grasp than a random number. Due to the limited space on the screen, the complete date won't fit. I will consider using a short date format when eventTime - currentTime is greater than 3 days, e.g. 2012-01-13

**Comment by john-tornblom** [comment]
fixed in master
